/// <reference path="typings/tsd.d.ts" />
/// <reference path="./appmanager.interfaces.ts" />
/// <reference path="./appmanager.gulp.ts" />
/// <reference path="./appmanager.nginx.ts" />
var gulp = require("gulp");
var path = require("path");
var pr = require("pushrocks");
var appmanager = {};
module.exports = appmanager;
//# sourceMappingURL=index.js.map